apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ui-ingress
spec:
  rules:
  - http:
      paths:
      - host: spark-ui.192.168.1.160.nip.io
        path: /
          pathType: Prefix
          backend:
            service:
              name: some-service
              port:
                number: 80