apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nessie-ingress
  labels:
    app: nessie
spec:
  ingressClassName: public
  rules:
  - host: nessie.192.168.1.160.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nessie
            port:
              number: 19120