apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-cat
  name: rest-cat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-cat
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
      - image: apache/iceberg-rest-fixture:1.9.2
        name: rest-cat
        ports:
        - containerPort: 8181
          name: rest
          protocol: TCP
        env:
        - name: CATALOG_IO__IMPL
          value: org.apache.iceberg.aws.s3.S3FileIO
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rest-cat-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rest-cat-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: rest-cat-secret
              key: AWS_REGION
        - name: CATALOG_WAREHOUSE
          valueFrom:
            secretKeyRef:
              name: rest-cat-secret
              key: CATALOG_WAREHOUSE
        - name: CATALOG_S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: rest-cat-secret
              key: CATALOG_S3_ENDPOINT