apiVersion: v3
dependencies: 
- name: trino
  repository: "https://trinodb.github.io/charts/"
  version: 1.39.1
description: "lkjglkejreljlrtj"
name: trino
type: application
appVersion: "1.0.0"
version: 0.0.0
