apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata: 
  name: vs-pgnessie-secret
spec:
  vaultAuthRef: vault-auth
  mount: lakehouse
  path: inf-postgres/pgnessie-secret
  type: kv-v2
  refreshAfter: 20m
  destination:
    name: pgnessie-secret
    create: true
    labels:
    transformation:
      excludeRaw: true